-- name: dsc-view
SELECT 
		TS.ID					AS ID,
		TS.SYSTEM_NAME 				AS SYSTEM_NAME,
		TS.ITAM_ID					AS ITAM_ID,
		TP.FIRST_NAME||' '||TP.LAST_NAME 			AS DATASET_CUSTODIAN,
		TP.BANK_ID					AS BANK_ID,
		COUNT(DISTINCT TS.SYSTEM_NAME) OVER ()		AS COUNT_SYSTEM_NAME,
		COUNT(DISTINCT TS.ITAM_ID) OVER ()			AS COUNT_ITAM_ID,
		COUNT(DISTINCT TP.FIRST_NAME||' '||TP.LAST_NAME) OVER ()	AS COUNT_DATASET_CUSTODIAN,
		COUNT(DISTINCT TP.BANK_ID) OVER ()			AS COUNT_BANK_ID
	FROM 
		TBL_EDMP_SYSTEM TS 
		INNER JOIN TBL_EDMP_LINK_ROLE_PEOPLE TLRP ON TLRP.OBJECT_ID = TS.ID AND TLRP.OBJECT_TYPE = 'SYSTEM'
		INNER JOIN TBL_EDMP_ROLE RL_SYS ON TLRP.ROLE_ID = RL_SYS.ID AND UPPER(RL_SYS.ROLE_NAME) = 'DATASET CUSTODIAN'
		INNER JOIN TBL_EDMP_PEOPLE TP ON TLRP.PEOPLE_ID = TP.ID 
	WHERE ('ALL' = '?' OR TP.BANK_ID = '?') AND TS.STATUS = 1
	ORDER BY TS.SYSTEM_NAME

-- name: dsc-view-homepage
/*
SELECT DISTINCT 
		CDE_COUNT, DSP_COUNT, INTERFACE_COUNT, POLICY_COUNT
	FROM (
		SELECT 
				COUNT(DISTINCT TMCD.ALIAS_NAME) 		AS CDE_COUNT
			FROM 
				TBL_EDMP_SYSTEM TS
				INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
				INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
				INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
				INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
			WHERE UPPER(TS.SYSTEM_NAME) = UPPER('?') AND CDE = 1
	) CDE , (
		SELECT 
				COUNT(DISTINCT NVL(DSP.NAME, ' ')) 		AS DSP_COUNT
			FROM 
				TBL_EDMP_SYSTEM TS
				INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
				INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
				INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
				INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
				LEFT OUTER JOIN TBL_DS_PROCESS_DETAIL DSPD ON DSPD.COLUMN_ID = TMC.ID
				LEFT OUTER JOIN TBL_DS_PROCESSES DSP ON DSPD.PROCESS_ID = DSP.ID
			WHERE UPPER(TS.SYSTEM_NAME) = UPPER('?') AND CDE = 1
	) DSP, (
		SELECT 
				COUNT(DISTINCT SS.SYSTEM_NAME) 		AS INTERFACE_COUNT
			FROM 
				TBL_EDMP_SYSTEM TS
				INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
				INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
				INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
				INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
				INNER JOIN TBL_LINK_COLUMN_INTERFACE CI ON CI.COLUMN_ID = TMC.ID
			INNER JOIN TBL_SYSTEM SS ON CI.IMM_SUCC_SYSTEM_ID = SS.ID
			WHERE UPPER(TS.SYSTEM_NAME) = UPPER('?') AND CDE = 1
	) INTERFACE, 
	(
	SELECT COUNT(DISTINCT POL.INFO_ASSET_NAME) AS POLICY_COUNT 
	FROM TBL_POLICY POL 
	INNER JOIN TBL_LINK_POLICY_SYSTEM PSYS ON POL.ID = PSYS.POLICY_ID 
	INNER JOIN TBL_EDMP_SYSTEM SYS ON PSYS.SYSTEM_ID = SYS.ID
	WHERE UPPER(SYS.SYSTEM_NAME) = UPPER('?')
	)

-- name: dsc-view-cde
SELECT 
		TMC.ID										AS ID,
		TMT.ID										AS TMTID,
		TS.ID										AS TSID,
		TMC.ID										AS COLID,
		TS.SYSTEM_NAME								AS SYSTEM_NAME,
		TMCD.ALIAS_NAME								AS CDE,
		TMCD.DESCRIPTION							AS DESCRIPTION,
		IPS.SYSTEM_NAME								AS UPSTREAM_SYSTEM,
		TMT.DISPLAY_NAME							AS TABLE_NAME,
		TMC.DISPLAY_NAME							AS COLUMN_NAME,
		NVL(TDP.NAME,' ')							AS DSP_NAME,
		TP.FIRST_NAME||' '|| TP.LAST_NAME        	AS PROCESS_OWNER,
		TP.BANK_ID									AS BANK_ID,
		COUNT(DISTINCT TMCD.ALIAS_NAME) OVER ()		AS COUNT_CDE,
		COUNT(DISTINCT NVL(TDP.NAME,' ')) OVER ()	AS COUNT_DSP_NAME
	FROM
		TBL_SYSTEM TS
		INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
		INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
		INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
		INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
		LEFT OUTER JOIN TBL_DS_PROCESS_DETAIL TDPD ON TDPD.COLUMN_ID = TMC.ID
		LEFT OUTER JOIN TBL_DS_PROCESSES TDP ON  TDP.ID = TDPD.PROCESS_ID
		LEFT OUTER JOIN TBL_LINK_ROLE_PEOPLE TLRP ON TLRP.OBJECT_ID = TDP.ID AND TLRP.OBJECT_TYPE = 'PROCESSES'
		LEFT OUTER JOIN TBL_ROLE RL ON TLRP.ROLE_ID = RL.ID AND UPPER(RL.ROLE_NAME) = 'DOWNSTREAM PROCESS OWNER'
		LEFT OUTER JOIN TBL_PEOPLE TP ON TLRP.PEOPLE_ID = TP.ID
		LEFT OUTER JOIN TBL_LINK_COLUMN_INTERFACE CI ON CI.COLUMN_ID = TMC.ID
		LEFT OUTER JOIN TBL_SYSTEM IPS ON IPS.ID = CI.IMM_PREC_SYSTEM_ID
		WHERE UPPER(TS.SYSTEM_NAME) = UPPER('?') AND CDE = 1
		GROUP BY TMC.ID,TMT.ID,TS.ID,TMC.ID,TS.SYSTEM_NAME,TMCD.ALIAS_NAME,TMCD.DESCRIPTION,IPS.SYSTEM_NAME,TMT.DISPLAY_NAME,TMC.DISPLAY_NAME,NVL(TDP.NAME,' '),TP.FIRST_NAME||' '||TP.LAST_NAME, TP.BANK_ID

-- name: dsc-view-cdp
SELECT  DISTINCT
		TDP.ID															AS ID,
		TS.SYSTEM_NAME													AS SYSTEM_NAME,
		NVL(TDP.NAME, ' ')                              				AS DSP_NAME,
		TP.FIRST_NAME||' '|| TP.LAST_NAME     							AS PROCESS_OWNER,
		TP.BANK_ID                            							AS BANK_ID,
		COUNT(DISTINCT TMCD.ALIAS_NAME) OVER (PARTITION BY TDP.NAME)	AS CDE_COUNT,
		COUNT(DISTINCT TMCD.ALIAS_NAME) OVER () 						AS TOTAL,
		COUNT(DISTINCT NVL(TDP.NAME, ' ')) OVER ()	  					AS COUNT_DSP_NAME
	FROM 
		TBL_SYSTEM TS
		INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
		INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
		INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
		INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
		LEFT OUTER JOIN TBL_DS_PROCESS_DETAIL TDPD ON TDPD.COLUMN_ID = TMC.ID
		LEFT OUTER JOIN TBL_DS_PROCESSES TDP ON  TDP.ID = TDPD.PROCESS_ID
		LEFT OUTER JOIN TBL_LINK_ROLE_PEOPLE TLRP ON TLRP.OBJECT_ID = TDP.ID AND TLRP.OBJECT_TYPE = 'PROCESSES'
		LEFT OUTER JOIN TBL_ROLE RL ON TLRP.ROLE_ID = RL.ID AND UPPER(RL.ROLE_NAME) = 'DOWNSTREAM PROCESS OWNER'
		LEFT OUTER JOIN TBL_PEOPLE TP ON TLRP.PEOPLE_ID = TP.ID
	WHERE UPPER(TS.SYSTEM_NAME) = UPPER('?') AND CDE = 1

-- name: dsc-view-cdp-cde
SELECT  DISTINCT 
		TMC.ID												AS ID,
		TMT.ID												AS TMTID,
		TS.ID												AS TSID,
		TMC.ID												AS COLID,
		TS.SYSTEM_NAME										AS SYSTEM_NAME,
		TDP.NAME                              				AS DSP_NAME,
		TP.FIRST_NAME||' '|| TP.LAST_NAME     				AS PROCESS_OWNER,
		TP.BANK_ID                            				AS BANK_ID,
		COUNT(DISTINCT TMCD.ALIAS_NAME) OVER ()     		AS CDE_COUNT,
		TMCD.ALIAS_NAME                        				AS CDE,
		TMCD.DESCRIPTION                       				AS DESCRIPTION,
		TMT.DISPLAY_NAME									AS TABLE_NAME,
		TMC.DISPLAY_NAME									AS COLUMN_NAME,
		COUNT(DISTINCT NVL(TMCD.ALIAS_NAME, ' ')) OVER ()	AS COUNT_CDE
	FROM 
		TBL_SYSTEM TS
		INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
		INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
		INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
		INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
		LEFT OUTER JOIN TBL_DS_PROCESS_DETAIL TDPD ON TDPD.COLUMN_ID = TMC.ID
		LEFT OUTER JOIN TBL_DS_PROCESSES TDP ON  TDP.ID = TDPD.PROCESS_ID
		LEFT OUTER JOIN TBL_LINK_ROLE_PEOPLE TLRP ON TLRP.OBJECT_ID = TDP.ID AND TLRP.OBJECT_TYPE = 'PROCESSES'
		LEFT OUTER JOIN TBL_ROLE RL ON TLRP.ROLE_ID = RL.ID AND UPPER(RL.ROLE_NAME) = 'DOWNSTREAM PROCESS OWNER'
		LEFT OUTER JOIN TBL_PEOPLE TP ON TLRP.PEOPLE_ID = TP.ID
	WHERE UPPER(TS.SYSTEM_NAME) = UPPER('?') AND CDE = 1 AND NVL(UPPER(TDP.NAME), ' ') = UPPER('?')

-- name: dsc-view-interfaces
SELECT ID, SYSTEM_NAME, IMM_INTERFACE, CDE_COUNT, COUNT_IMM_INTERFACE, PROCESS_OWNER
FROM (
	SELECT  DISTINCT
		SS.ID,
		UPPER(TS.SYSTEM_NAME)                     		AS SYSTEM_NAME,
		COUNT(DISTINCT SS.SYSTEM_NAME) OVER()     	AS INTERFACE_COUNT,
		SS.SYSTEM_NAME                            		AS IMM_INTERFACE,
		COUNT(DISTINCT TMCD.ALIAS_NAME) OVER(PARTITION BY SS.SYSTEM_NAME)      	   	AS CDE_COUNT,
		COUNT(DISTINCT SS.SYSTEM_NAME) OVER ()	AS COUNT_IMM_INTERFACE,
		TP.FIRST_NAME||' '||TP.LAST_NAME     		AS PROCESS_OWNER
	FROM 
		TBL_SYSTEM TS
		INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
		INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
		INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
		INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
		INNER JOIN TBL_LINK_COLUMN_INTERFACE CI ON CI.COLUMN_ID = TMC.ID
		INNER JOIN TBL_SYSTEM SS ON CI.IMM_SUCC_SYSTEM_ID = SS.ID
		LEFT OUTER JOIN TBL_LINK_ROLE_PEOPLE TLRP ON TLRP.OBJECT_ID = SS.ID AND TLRP.OBJECT_TYPE = 'SYSTEM'
		LEFT OUTER JOIN TBL_ROLE RL_SYS ON TLRP.ROLE_ID = RL_SYS.ID AND UPPER(RL_SYS.ROLE_NAME) = 'DATASET CUSTODIAN'
		LEFT OUTER JOIN TBL_PEOPLE TP ON TLRP.PEOPLE_ID = TP.ID  
	WHERE UPPER(TS.SYSTEM_NAME) = UPPER('?')
) RES WHERE CDE_COUNT <> 0
ORDER BY IMM_INTERFACE, PROCESS_OWNER

-- name: dsc-view-interfaces-cde
SELECT  DISTINCT 
		SS.ID										AS ID,
		TMT.ID										AS TMTID,
		TS.ID										AS TSID,
		TMC.ID										AS COLID,
		UPPER(TS.SYSTEM_NAME)						AS SYSTEM_NAME,
		SS.SYSTEM_NAME								AS IMM_INTERFACE,
		COUNT(DISTINCT TMCD.ALIAS_NAME) OVER ()		AS CDE_COUNT,
		TMCD.ALIAS_NAME                        		AS CDE,
		TMCD.DESCRIPTION							AS DESCRIPTION,
		TMT.DISPLAY_NAME							AS TABLE_NAME,
		TMC.DISPLAY_NAME							AS COLUMN_NAME,
		COUNT(DISTINCT TMCD.ALIAS_NAME) OVER ()		AS COUNT_CDE,
		PS.SYSTEM_NAME								AS IMM_PREC_SYSTEM,
		SS.SYSTEM_NAME								AS IMM_SUCC_SYSTEM		
	FROM 
		TBL_SYSTEM TS
		INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
		INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
		INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
		INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
		INNER JOIN TBL_LINK_COLUMN_INTERFACE CI ON CI.COLUMN_ID = TMC.ID
		INNER JOIN TBL_SYSTEM SS ON CI.IMM_SUCC_SYSTEM_ID = SS.ID
		LEFT OUTER JOIN TBL_SYSTEM PS ON CI.IMM_PREC_SYSTEM_ID = PS.ID
	WHERE UPPER(TS.SYSTEM_NAME) = UPPER('?') AND UPPER(SS.SYSTEM_NAME) = UPPER('?')

-- name: details-left-panel
SELECT DISTINCT
		TS.ID								AS ID,
		TMT.ID								AS TMTID,
		TMC.ID								AS TMCID,
		TS.SYSTEM_NAME						AS SYSTEM_NAME,
		TS.ITAM_ID							AS ITAM_ID,
		TP.FIRST_NAME||' '||TP.LAST_NAME	AS DATASET_CUSTODIAN,
		TP.BANK_ID							AS BANK_ID,
		TMCD.ALIAS_NAME						AS BUSINESS_ALIAS_NAME,
		TMT.DISPLAY_NAME 					AS TABLE_NAME,
		TMC.DISPLAY_NAME					AS COLUMN_NAME
	FROM
		TBL_SYSTEM TS
		LEFT JOIN TBL_LINK_ROLE_PEOPLE TLRP ON TLRP.OBJECT_ID = TS.ID AND TLRP.OBJECT_TYPE = 'SYSTEM'
		LEFT JOIN TBL_ROLE RL_SYS ON TLRP.ROLE_ID = RL_SYS.ID AND RL_SYS.ROLE_NAME = 'DATASET CUSTODIAN'
		LEFT JOIN TBL_PEOPLE TP ON TLRP.PEOPLE_ID = TP.ID
		INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
		INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
		INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
		INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
	WHERE 
		TS.ID = '?'

-- name: details
SELECT DISTINCT
		TS.ID									AS ID,
		TMT.ID									AS TMTID,
		TMC.ID									AS TMCID,
		TS.SYSTEM_NAME							AS SYSTEM_NAME,
		TMCD.ALIAS_NAME							AS BUSINESS_ALIAS_NAME,
		TMT.DISPLAY_NAME 						AS TABLE_NAME,
		TMC.DISPLAY_NAME						AS COLUMN_NAME,
		TMCD.DESCRIPTION 						AS BUSINESS_ALIAS_DESCRIPTION,
		TMCD.CDE								AS CDE_YES_NO,
		TMCD.STATUS								AS STATUS,
		TMC.DATA_TYPE							AS DATA_TYPE,
		TMC.DATA_FORMAT							AS DATA_FORMAT,
		TMC.DATA_LENGTH							AS DATA_LENGTH,
		TMCD.EXAMPLE							AS EXAMPLE,
		TMCD.DERIVED							AS DERIVED_YES_NO,
		TMCD.DERIVATION_LOGIC					AS DERIVATION_LOGIC,
		TMCD.SOURCED_FROM_UPSTREAM				AS SOURCED_FROM_UPSTREAM_YES_NO,
		TMCD.SYSTEM_CHECKS						AS SYSTEM_CHECKS,
		TC.NAME 								AS DOMAIN,
		TSC.NAME 								AS SUBDOMAIN,
		PPL.FIRST_NAME||' '||PPL.LAST_NAME 		AS DOMAIN_OWNER,
		TBT.BT_NAME								AS BUSINESS_TERM,
		TBT.DESCRIPTION 						AS BUSINESS_TERM_DESCRIPTION,
		TPOL.INFO_ASSET_NAME					AS INFORMATION_ASSET_NAMES,
		TPOL.DESCRIPTION 						AS INFORMATION_ASSET_DESCRIPTION,
		TPOL.CONFIDENTIALITY					AS CONFIDENTIALITY,
		TPOL.INTEGRITY							AS INTEGRITY,
		TPOL.AVAILABILITY						AS AVAILABILITY,
		TPOL.OVERALL_CIA_RATING					AS OVERALL_CIA_RATING,
		TMT.RECORD_CATEGORY						AS RECORD_CATEGORIES,
		TMCD.PII_FLAG							AS PII_FLAG,
		IPS.SYSTEM_NAME 						AS IMM_PRECEEDING_SYSTEM,
		CI.INCOMING_CDE_NAME					AS IMM_PREC_INCOMING,
		CI.INCOMING_DERIVED						AS IMM_PREC_DERIVED,
		CI.INCOMING_DERIVATION_LOGIC			AS IMM_PREC_DERIVATION_LOGIC,
		ISS.SYSTEM_NAME 						AS IMM_SUCCEEDING_SYSTEM,
		CI.OUTGOING_CDE_NAME					AS IMM_SUCC_INCOMING,
		CI.OUTGOING_DERIVED						AS IMM_SUCC_DERIVED,
		CI.OUTGOING_DERIVATION_LOGIC			AS IMM_SUCC_DERIVATION_LOGIC,
		TMCD.DQ_STANDARDS||' '||TMCD.THRESHOLD	AS THRESHOLD
	FROM  
		TBL_SYSTEM TS
		LEFT JOIN TBL_LINK_ROLE_PEOPLE TLRP ON TLRP.OBJECT_ID = TS.ID AND TLRP.OBJECT_TYPE = 'SYSTEM'
		LEFT JOIN TBL_ROLE RL_SYS ON TLRP.ROLE_ID = RL_SYS.ID AND RL_SYS.ROLE_NAME = 'DATASET CUSTODIAN'
		LEFT JOIN TBL_PEOPLE TP ON TLRP.PEOPLE_ID = TP.ID
		INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
		INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
		INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
    	INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
		LEFT JOIN TBL_LINK_COLUMN_BUSINESS_TERM LCBT ON TMC.ID = LCBT.COLUMN_ID 
		LEFT JOIN TBL_BUSINESS_TERM TBT ON LCBT.BUSINESS_TERM_ID = TBT.ID
		LEFT JOIN TBL_SUBCATEGORY TSC ON TBT.PARENT_ID = TSC.ID
		LEFT JOIN TBL_LINK_ROLE_PEOPLE TLRP_SDO ON TLRP_SDO.OBJECT_ID = TSC.ID AND TLRP_SDO.OBJECT_TYPE = 'SUBCATEGORY'
		LEFT JOIN TBL_ROLE RL ON TLRP_SDO.ROLE_ID = RL.ID AND RL.ROLE_NAME = 'DATA DOMAIN OWNER'
		LEFT JOIN TBL_PEOPLE PPL ON TLRP_SDO.PEOPLE_ID = PPL.ID
		LEFT JOIN TBL_POLICY TPOL ON TBT.POLICY_ID = TPOL.ID
		LEFT JOIN TBL_LINK_COLUMN_INTERFACE CI ON TMC.ID = CI.COLUMN_ID
		LEFT JOIN TBL_SYSTEM IPS ON CI.IMM_PREC_SYSTEM_ID = IPS.ID
		LEFT JOIN TBL_SYSTEM ISS ON CI.IMM_SUCC_SYSTEM_ID = ISS.ID
		LEFT JOIN TBL_CATEGORY TC ON TSC.CATEGORY_ID = TC.ID
		INNER JOIN
		(
			SELECT
			DISTINCT TS.ID AS SYS_ID, TMR.ID AS RES_ID, TMT.ID AS TAB_ID
			FROM TBL_SYSTEM TS
				INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
				INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
				INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
        				INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
			WHERE 
				TS.ID = '?'
				AND CDE = 1
		) CDE ON TS.ID = CDE.SYS_ID AND TMR.ID = CDE.RES_ID AND TMT.ID = CDE.TAB_ID
	ORDER BY TMT.DISPLAY_NAME, TMC.DISPLAY_NAME


-- name: dsc-view-dd
SELECT DISTINCT
		TS.ID																AS ID,
		TMT.ID																AS TMTID,
		TMC.ID																AS TMCID,
		TS.SYSTEM_NAME														AS SYSTEM_NAME,
		TMCD.ALIAS_NAME														AS BUSINESS_ALIAS_NAME,
		TMT.DISPLAY_NAME													AS TABLE_NAME,
		TMC.DISPLAY_NAME													AS COLUMN_NAME,
		TMCD.DESCRIPTION													AS BUSINESS_ALIAS_DESCRIPTION,
		CASE WHEN TMCD.CDE = 1 THEN 'Yes' ELSE 'No' END						AS CDE_YES_NO,
		TMC.DATA_TYPE														AS DATA_TYPE,
		TMC.DATA_LENGTH														AS DATA_LENGTH,
		TMCD.EXAMPLE														AS EXAMPLE,
		CASE WHEN TMCD.DERIVED = 1 THEN 'Yes' ELSE 'No' END					AS DERIVED_YES_NO,
		TMCD.DERIVATION_LOGIC												AS DERIVATION_LOGIC,
		CASE WHEN TMCD.SOURCED_FROM_UPSTREAM = 1 THEN 'Yes' ELSE 'No' END	AS SOURCED_FROM_UPSTREAM_YES_NO,
		TMCD.SYSTEM_CHECKS													AS SYSTEM_CHECKS,
		TC.NAME																AS DOMAIN,
		TSC.NAME															AS SUBDOMAIN,
		PPL.FIRST_NAME||' '||PPL.LAST_NAME									AS DOMAIN_OWNER,
		TBT.BT_NAME															AS BUSINESS_TERM,
		TBT.DESCRIPTION 													AS BUSINESS_TERM_DESCRIPTION
	FROM 
		TBL_SYSTEM TS
		INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
		INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
		INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
		INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID		
		LEFT JOIN TBL_LINK_COLUMN_BUSINESS_TERM LCBT ON TMC.ID = LCBT.COLUMN_ID 
		LEFT JOIN TBL_BUSINESS_TERM TBT ON LCBT.BUSINESS_TERM_ID = TBT.ID
		LEFT JOIN TBL_SUBCATEGORY TSC ON TBT.PARENT_ID = TSC.ID
		LEFT JOIN TBL_LINK_ROLE_PEOPLE TLRP_SDO ON TLRP_SDO.OBJECT_ID = TSC.ID AND TLRP_SDO.OBJECT_TYPE = 'SUBCATEGORY'
		LEFT JOIN TBL_ROLE RL ON TLRP_SDO.ROLE_ID = RL.ID AND UPPER(RL.ROLE_NAME) = 'DATA DOMAIN OWNER'
		LEFT JOIN TBL_PEOPLE PPL ON TLRP_SDO.PEOPLE_ID = PPL.ID
		LEFT JOIN TBL_CATEGORY TC ON TSC.CATEGORY_ID = TC.ID
		INNER JOIN
		(
			SELECT
					DISTINCT TS.ID AS SYS_ID, TMR.ID AS RES_ID, TMT.ID AS TAB_ID
				FROM TBL_SYSTEM TS
					INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
					INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
					INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
        			INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
				WHERE 
					UPPER(TS.SYSTEM_NAME) = UPPER('?')
					AND CDE = 1
		) CDE ON TS.ID = CDE.SYS_ID AND TMR.ID = CDE.RES_ID AND TMT.ID = CDE.TAB_ID
	ORDER BY TMT.DISPLAY_NAME, TMC.DISPLAY_NAME
	
-- name: dsc-view-policy-ia
SELECT
  		TPOL.INFO_ASSET_NAME		AS INFORMATION_ASSET_NAMES,
		TPOL.DESCRIPTION 			AS INFORMATION_ASSET_DESCRIPTION,
		TPOL.CONFIDENTIALITY		AS CONFIDENTIALITY,
		TPOL.INTEGRITY				AS INTEGRITY,
		TPOL.AVAILABILITY			AS AVAILABILITY,
		TPOL.OVERALL_CIA_RATING		AS OVERALL_CIA_RATING
FROM 
	TBL_POLICY TPOL 
	INNER JOIN TBL_LINK_POLICY_SYSTEM PSYS ON TPOL.ID = PSYS.POLICY_ID 
	INNER JOIN TBL_SYSTEM SYS ON PSYS.SYSTEM_ID = SYS.ID
	WHERE UPPER(SYS.SYSTEM_NAME) = UPPER('?')

-- name: dsc-view-policy
SELECT DISTINCT
		TS.ID													AS ID,
		TMT.ID													AS TMTID,
		TMC.ID													AS TMCID,
		TMT.DISPLAY_NAME										AS TABLE_NAME,
		TMC.DISPLAY_NAME										AS COLUMN_NAME,
		TMCD.ALIAS_NAME											AS BUSINESS_ALIAS_NAME,
		TMCD.DESCRIPTION										AS BUSINESS_ALIAS_DESCRIPTION,
		CASE WHEN TMCD.CDE = 1 THEN 'Yes' ELSE 'No' END			AS CDE_YES_NO,
		CASE WHEN TMCD.PII_FLAG = 1 THEN 'Yes' ELSE 'No' END	AS PII_FLAG
	FROM 
		TBL_SYSTEM TS
		INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
		INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
		INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
		INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID		
		INNER JOIN
		(
			SELECT
					DISTINCT TS.ID AS SYS_ID, TMR.ID AS RES_ID, TMT.ID AS TAB_ID
				FROM TBL_SYSTEM TS
					INNER JOIN TBL_MD_RESOURCE TMR ON TS.ID = TMR.SYSTEM_ID
					INNER JOIN TBL_MD_TABLE TMT ON TMR.ID = TMT.RESOURCE_ID
					INNER JOIN TBL_MD_COLUMN TMC ON TMT.ID = TMC.TABLE_ID
        			INNER JOIN TBL_MD_COLUMN_DETAILS TMCD ON TMCD.COLUMN_ID = TMC.ID
				WHERE 
					UPPER(TS.SYSTEM_NAME) = UPPER('?')
					AND CDE = 1
		) CDE ON TS.ID = CDE.SYS_ID AND TMR.ID = CDE.RES_ID AND TMT.ID = CDE.TAB_ID
	ORDER BY TMT.DISPLAY_NAME, TMC.DISPLAY_NAME
*/