-- name: edmp-dd-dropdowns
SELECT DISTINCT
        COUNTRY AS COUNTRY,
        BUSINESS_SEGMENT AS BUSINESS_SEGMENT,
        SOURCE_SYSTEM AS SOURCE_SYSTEM,
        CLUSTER_NAME AS CLUSTER_NAME,
        TIER AS TIER,
        ITAM AS ITAM
    FROM
        TBL_EDMP

-- name: edmp-dd-technical
SELECT DISTINCT
        COUNTRY AS COUNTRY,
        BUSINESS_SEGMENT AS BUSINESS_SEGMENT,
        SOURCE_SYSTEM AS SOURCE_SYSTEM,
        CLUSTER_NAME AS CLUSTER_NAME,
        TIER AS TIER,
        ITAM AS ITAM,
        EDM_SOURCE_SYSTEM_NAME AS EDM_SOURCE_SYSTEM_NAME,
        DATABASE_NAME AS DATABASE_NAME,
        TABLE_NAME AS TABLE_NAME,
        COLUMN_NAME AS COLUMN_NAME,
        DATA_TYPE AS DATA_TYPE,
        '' AS COLUMN_LENGTH,
        NULLABLE AS NULLABLE,
        PRIMARY_KEY AS PRIMARY_KEY,
        CERTIFIED AS CERTIFIED,
        PROFILE_RESULTS AS PROFILE_RESULTS,
        DATA_LINEAGE AS DATA_LINEAGE,
        '' AS BUSINESS_ALIAS_NAME,
        '' AS BUSINESS_ALIAS_DESCRIPTION,
        CDE AS CDE,
        DATA_LENGTH AS DATA_LENGTH,
        '' AS EXAMPLE,
        '' AS DERIVED,
        '' AS DERIVATION_LOGIC,
        '' AS SOURCED_FROM_UPSTREAM,
        '' AS SYSTEM_CHECKS
    FROM
        TBL_EDMP

-- name: edmp-dd-business
SELECT DISTINCT
        COUNTRY AS COUNTRY,
        SOURCE_SYSTEM AS SOURCE_SYSTEM,
        CLUSTER_NAME AS CLUSTER_NAME,
        TIER AS TIER,
        ITAM AS ITAM,
        EDM_SOURCE_SYSTEM_NAME AS EDM_SOURCE_SYSTEM_NAME,
        DATABASE_NAME AS DATABASE_NAME,
        TABLE_DESCRIPTION AS TABLE_DESCRIPTION,
        COLUMN_DESCRIPTION AS COLUMN_DESCRIPTION,
        BUSINESS_TERM AS BUSINESS_TERM,
        BUSINESS_DESCRIPTION AS BUSINESS_DESCRIPTION,
        DETERMINES_CLIENT_LOCATION AS DETERMINES_CLIENT_LOCATION,
        DETERMINES_ACCOUNT AS DETERMINES_ACCOUNT,
        BUSINESS_SEGMENT AS BUSINESS_SEGMENT,
        PRODUCT_CATEGORY AS PRODUCT_CATEGORY,
        TABLE_NAME AS TABLE_NAME,
        COLUMN_NAME AS COLUMN_NAME,
        '' AS BUSINESS_ALIAS_NAME,
        '' AS BUSINESS_ALIAS_DESCRIPTION,
        CDE AS CDE,
        '' AS DOMAIN,
        '' AS SUBDOMAIN,
        '' AS DOMAIN_OWNER,
        '' AS BUSINESS_TERM_DESCRIPTION
    FROM
        TBL_EDMP

-- name: edmp-dd-consumption
SELECT DISTINCT
        COUNTRY AS COUNTRY,
        BUSINESS_SEGMENT AS BUSINESS_SEGMENT,
        SOURCE_SYSTEM AS SOURCE_SYSTEM,
        CLUSTER_NAME AS CLUSTER_NAME,
        TIER AS TIER,
        ITAM AS ITAM,
        EDM_SOURCE_SYSTEM_NAME AS EDM_SOURCE_SYSTEM_NAME,
        DATABASE_NAME AS DATABASE_NAME,
        TABLE_NAME AS TABLE_NAME,
        COLUMN_NAME AS COLUMN_NAME,
        CONSUMING_APPLICATION AS CONSUMING_APPLICATION,
        CONSUMING_APPLICATION_ITAM AS CONSUMING_APPLICATION_ITAM,
        CONSUMING_APPLICATION_OWNER AS CONSUMING_APPLICATION_OWNER,
        CONSUMER_DESCRIPTION AS CONSUMER_DESCRIPTION,
        TECH_CONTACT AS TECH_CONTACT,
        BUSINESS_OWNERSHIP AS BUSINESS_OWNERSHIP,
        ACCESS_ROLE AS ACCESS_ROLE,
        ROLE_DESCRIPTION AS ROLE_DESCRIPTION,
        CONSUMING_TECH_METADATA AS CONSUMING_TECH_METADATA
    FROM
        TBL_EDMP

-- name: edmp-iarc-personal
SELECT DISTINCT
        EDM_SOURCE_SYSTEM_NAME AS EDM_SOURCE_SYSTEM_NAME,
        DATABASE_NAME AS DATABASE_NAME,
        TABLE_NAME AS TABLE_NAME,
        COLUMN_NAME AS COLUMN_NAME,
        '' AS BUSINESS_ALIAS_NAME,
        '' AS BUSINESS_ALIAS_DESCRIPTION,
        PII AS PII,
        CDE AS CDE
    FROM
        TBL_EDMP