-- name: edmp-dd-dropdowns
SELECT
        COUNTRY AS COUNTRY,
        BUSINESS_SEGMENT AS BUSINESS_SEGMENT,
        EDM_SOURCE_SYSTEM_NAME AS EDM_SOURCE_SYSTEM_NAME,
        CLUSTER_NAME AS CLUSTER_NAME,
        TIER AS TIER,
        ITAM AS ITAM
    FROM
        TBL_EDMP

-- name: edmp-dd-technical
SELECT
        COUNTRY AS COUNTRY,
        BUSINESS_SEGMENT AS BUSINESS_SEGMENT,
        EDM_SOURCE_SYSTEM_NAME AS EDM_SOURCE_SYSTEM_NAME,
        CLUSTER_NAME AS CLUSTER_NAME,
        TIER AS TIER,
        ITAM AS ITAM,
        DATABASE_NAME AS DATABASE_NAME,
        TABLE_NAME AS TABLE_NAME,
        COLUMN_NAME AS COLUMN_NAME,
        DATA_TYPE AS DATA_TYPE,
        DATA_LENGTH AS COLUMN_LENGTH,
        NULLABLE AS NULLABLE,
        PRIMARY_KEY AS PRIMARY_KEY,
        CERTIFIED AS CERTIFIED,
        DATA_XRAY AS DATA_XRAY,
        PII AS PII,
        DATA_LINEAGE AS DATA_LINEAGE,
        CDE AS CDE
    FROM
        TBL_EDMP

-- name: edmp-dd-business
SELECT
        COUNTRY AS COUNTRY,
        EDM_SOURCE_SYSTEM_NAME AS EDM_SOURCE_SYSTEM_NAME,
        CLUSTER_NAME AS CLUSTER_NAME,
        TIER AS TIER,
        ITAM AS ITAM,
        DATABASE_NAME AS DATABASE_NAME,
        TABLE_NAME AS TABLE_NAME,
        TABLE_DESCRIPTION AS TABLE_DESCRIPTION,
        COLUMN_NAME AS COLUMN_NAME,
        COLUMN_DESCRIPTION AS COLUMN_DESCRIPTION,
        BUSINESS_TERM AS BUSINESS_TERM,
        BUSINESS_DESCRIPTION AS BUSINESS_DESCRIPTION,
        DETERMINES_CLIENT_LOCATION AS DETERMINES_CLIENT_LOCATION,
        DETERMINES_ACCOUNT AS DETERMINES_ACCOUNT,
        BUSINESS_SEGMENT AS BUSINESS_SEGMENT,
        PRODUCT_CATEGORY AS PRODUCT_CATEGORY,
        CDE AS CDE
     FROM
        TBL_EDMP

-- name: edmp-dd-consumption
SELECT
        COUNTRY AS COUNTRY,
        BUSINESS_SEGMENT AS BUSINESS_SEGMENT,
        EDM_SOURCE_SYSTEM_NAME AS EDM_SOURCE_SYSTEM_NAME,
        CLUSTER_NAME AS CLUSTER_NAME,
        TIER AS TIER,
        ITAM AS ITAM,
        DATABASE_NAME AS DATABASE_NAME,
        TABLE_NAME AS TABLE_NAME,
        COLUMN_NAME AS COLUMN_NAME,
        CONSUMING_APPLICATION AS CONSUMING_APPLICATION,
        CONSUMING_APPLICATION_ITAM AS CONSUMING_APPLICATION_ITAM,
        CONSUMING_APPLICATION_OWNER AS CONSUMING_APPLICATION_OWNER,
        CONSUMER_DESCRIPTION AS CONSUMER_DESCRIPTION,
        TECH_CONTACT AS TECH_CONTACT,
        BUSINESS_OWNERSHIP AS BUSINESS_OWNERSHIP,
        ACCESS_ROLE AS ACCESS_ROLE,
        ROLE_DESCRIPTION AS ROLE_DESCRIPTION,
        CONSUMING_TECH_METADATA AS CONSUMING_TECH_METADATA
    FROM
        TBL_EDMP

-- name: edmp-iarc-dropdowns
SELECT
        COUNTRY AS COUNTRY,
        EDM_SOURCE_SYSTEM_NAME AS EDM_SOURCE_SYSTEM_NAME,
        ITAM AS ITAM
    FROM
        TBL_EDMP

-- name: edmp-iarc-personal
SELECT
        COUNTRY AS COUNTRY,
        ITAM AS ITAM,
        EDM_SOURCE_SYSTEM_NAME AS EDM_SOURCE_SYSTEM_NAME,
        DATABASE_NAME AS DATABASE_NAME,
        TABLE_NAME AS TABLE_NAME,
        COLUMN_NAME AS COLUMN_NAME,
        PII AS PII,
        CDE AS CDE
    FROM
        TBL_EDMP