-- name: rfo-view
SELECT DISTINCT
    CAT.ID,
    CAT.NAME                          AS PRINCIPAL_RISK_TYPES,
	  SC.NAME                           AS RISK_SUB_TYPE,    
    PO.FIRST_NAME||' '||PO.LAST_NAME 	AS RISK_FRAMEWORK_OWNER,
    PL.FIRST_NAME||' '||PL.LAST_NAME 	AS RISK_REPORTING_LEAD,    
    COUNT(DISTINCT UPPER(PR.NAME)) OVER (PARTITION BY CAT.NAME, SC.NAME)   AS PR_COUNT,
    COUNT(DISTINCT UPPER(CRM.NAME)) OVER (PARTITION BY CAT.NAME, SC.NAME)  AS CRM_COUNT,
    COUNT(DISTINCT UPPER(CDE.NAME)) OVER (PARTITION BY CAT.NAME, SC.NAME)  AS CDE_COUNT
FROM TBL_PRIORITY_REPORTS PR 
    INNER JOIN TBL_PEOPLE PO ON PR.OWNER_ID = PO.ID
    INNER JOIN TBL_PEOPLE PL ON PR.LEAD_ID = PL.ID
    INNER JOIN TBL_SUBCATEGORY SC ON PR.SUB_RISK_TYPE_ID = SC.ID
    INNER JOIN TBL_CATEGORY CAT ON SC.CATEGORY_ID = CAT.ID
    INNER JOIN TBL_CRM CRM ON PR.ID = CRM.PRORITY_REPORT_ID
    INNER JOIN TBL_CDE CDE ON CDE.CRM_ID = CRM.ID
WHERE ('ALL' = '?' OR PO.BANK_ID = '?')
ORDER BY CAT.NAME, SC.NAME

-- name: rfo-home-view
SELECT
    CAT.NAME                        AS PRINCIPAL_RISK,
    SC.NAME                         AS RISK_SUB
FROM TBL_PRIORITY_REPORTS PR 
    INNER JOIN TBL_PEOPLE PL ON PR.LEAD_ID = PL.ID
    INNER JOIN TBL_SUBCATEGORY SC ON PR.SUB_RISK_TYPE_ID = SC.ID
    INNER JOIN TBL_CATEGORY CAT ON SC.CATEGORY_ID = CAT.ID
WHERE UPPER(SC.NAME) = upper('?') -- PASS SUB RISK TYPE IN UPPER CASE

-- name: rfo-summary-view
SELECT
    PR.ID,
    CAT.NAME                        AS PRINCIPAL_RISK,
    SC.NAME                         AS RISK_SUB,
    COUNT(DISTINCT PR.NAME) OVER () AS PR_COUNT,
    PR.NAME                         AS PRIORITY_REPORT,
    COUNT(DISTINCT CRM.NAME) OVER () AS CRM_COUNT,
	CRM.NAME                        AS CRM_NAME,
	COUNT(DISTINCT CDE.NAME) OVER () AS CDE_COUNT,	
    CDE.NAME                        AS CDE_NAME
FROM TBL_PRIORITY_REPORTS PR 
    INNER JOIN TBL_PEOPLE PL ON PR.LEAD_ID = PL.ID
    INNER JOIN TBL_SUBCATEGORY SC ON PR.SUB_RISK_TYPE_ID = SC.ID
    INNER JOIN TBL_CATEGORY CAT ON SC.CATEGORY_ID = CAT.ID
    INNER JOIN TBL_CRM CRM ON PR.ID = CRM.PRORITY_REPORT_ID
    INNER JOIN TBL_CDE CDE ON CDE.CRM_ID = CRM.ID
WHERE UPPER(SC.NAME) = upper('?') -- PASS SUB RISK TYPE IN UPPER CASE
ORDER BY PR.NAME, CRM.NAME, CDE.NAME

-- name: rfo-hierarchy-view
SELECT
    PR.ID,
    CAT.NAME                        AS PRINCIPAL_RISK,
    SC.NAME                         AS RISK_SUB,
    COUNT(DISTINCT PR.NAME) OVER () AS PR_COUNT,
    PR.NAME                         AS PRIORITY_REPORT,
    PR.RATIONALE                    AS PRIORITY_REPORT_RATIONALE,    
    CRM.NAME                        AS CRM_NAME,
    CRM.CRM_RATIONALE               AS CRM_RATIONALE,
    CDE.NAME                        AS CDE_NAME,
    CDE.CDE_RATIONALE               AS CDE_RATIONALE
FROM TBL_PRIORITY_REPORTS PR 
    INNER JOIN TBL_PEOPLE PL ON PR.LEAD_ID = PL.ID
    INNER JOIN TBL_SUBCATEGORY SC ON PR.SUB_RISK_TYPE_ID = SC.ID
    INNER JOIN TBL_CATEGORY CAT ON SC.CATEGORY_ID = CAT.ID
    INNER JOIN TBL_CRM CRM ON PR.ID = CRM.PRORITY_REPORT_ID
    INNER JOIN TBL_CDE CDE ON CDE.CRM_ID = CRM.ID
WHERE UPPER(SC.NAME) = upper('?') -- PASS SUB RISK TYPE IN UPPER CASE
ORDER BY PR.NAME, CRM.NAME, CDE.NAME