-- name: left-grid
SELECT * 
	FROM (
		SELECT * 
			FROM (
				SELECT res.*, 
						COUNT(DISTINCT PRIORITY_REPORT) OVER () COUNT_PRIORITY_REPORT,
						COUNT(DISTINCT RR_LEAD) OVER () COUNT_RR_LEAD,
						COUNT(DISTINCT BANK_ID) OVER () COUNT_BANK_ID
					FROM (
						SELECT DISTINCT
								PR.id,
								PR.NAME                               AS PRIORITY_REPORT, 
								PL.FIRST_NAME||' '|| PL.LAST_NAME     AS RR_LEAD,
								PL.BANK_ID                            AS BANK_ID
							FROM TBL_PRIORITY_REPORTS PR 
							INNER JOIN TBL_PEOPLE PL ON PR.LEAD_ID = PL.ID
						WHERE 
							PL.BANK_ID ='?'
					) res
			) WHERE ( -- Main filter and dropdown filter
				upper(PRIORITY_REPORT) LIKE upper('%?%')
				AND upper(RR_LEAD) LIKE upper('%?%')
			)
	) WHERE ( -- Column filter
		upper(PRIORITY_REPORT) LIKE upper('%?%')
		AND upper(RR_LEAD) LIKE upper('%?%')
		AND upper(BANK_ID) LIKE upper('%?%')
	)

-- name: right-grid
SELECT DISTINCT
  CAT.id,
  PR.id 	AS TPRID,
  CAT.NAME AS PRINCIPAL_RISK,
  SC.NAME AS RISK_SUB,
  PR.RATIONALE AS PR_RATIONALE,
  CRM.NAME AS CRM_NAME,
  CRM.CRM_RATIONALE,
  BT.BT_NAME AS ASSOC_CDES,
  BT.CDE_RATIONALE
FROM TBL_PRIORITY_REPORTS PR 
INNER JOIN TBL_PEOPLE PL ON PR.LEAD_ID = PL.ID
INNER JOIN TBL_SUBCATEGORY SC ON PR.SUB_RISK_TYPE_ID = SC.ID
INNER JOIN TBL_CATEGORY CAT ON SC.CATEGORY_ID = CAT.ID
INNER JOIN TBL_CRM CRM ON PR.ID = CRM.PRORITY_REPORT_ID
INNER JOIN TBL_LINK_CRM_CDE LNK ON LNK.CRM_ID = CRM.ID
INNER JOIN TBL_BUSINESS_TERM BT ON LNK.CDE_ID = BT.ID
WHERE pr.id = '?'
ORDER BY CRM.NAME, BT.BT_NAME
