import { fetchWHeader } from '../_helpers/auth-header';

export const rfoMyService = {
    getLeftTable,
    getRightTable,
    getAllRisk,
    getPriorityTable,
};

function getLeftTable(param) {
    return fetchWHeader(`/rfo/getlefttable`, param)
}

function getRightTable(param) {
    return fetchWHeader(`/rfo/getrighttable`, param).then(
        res => {
            res.Data = _.map(res.Data, function(v){
                v.LEFTID = v.TPRID;
                return v;
            });
            var tmp = _.groupBy(res.Data, "PRINCIPAL_RISK");

            res.Data = _.map(Object.keys(tmp), function(v, i){
                var tmp2 = _.groupBy(tmp[v], "RISK_SUB");

                var RiskSubTypes = _.map(Object.keys(tmp2), function(v, i){
                    var tmp3 = _.groupBy(tmp2[v], "PR_NAME");

                    var PriorityReports = _.map(Object.keys(tmp3), function(v, i){
                        var tmp4 = _.groupBy(tmp3[v], "CRM_NAME");

                        var CRMNames = _.map(Object.keys(tmp4), function(v, i){
                            var tmp5 = _.groupBy(tmp4[v], "ASSOC_CDES");

                            var CDEs = _.map(Object.keys(tmp5), function(v, i){
                                var ret = tmp5[v][0];
                                ret.ID = i
                                ret.ASSOC_CDES = v;
                                ret.Rationales = tmp5[v];

                                return ret;
                            });

                            var ret = tmp4[v][0];
                            ret.ID = i
                            ret.CRM_NAME = v;
                            ret.CDEs = CDEs;
                            ret.CDEsVal = tmp4[v];

                            return ret;
                        });

                        var ret = tmp3[v][0];
                        ret.ID = i
                        ret.PR_NAME = v;
                        ret.CRMNames = CRMNames;
                        ret.CRMNamesVal = tmp3[v];

                        return ret;
                    });

                    var ret = tmp2[v][0];
                    ret.ID = i
                    ret.RISK_SUB = v;
                    ret.PriorityReports = PriorityReports;
                    ret.PriorityReportsVal = tmp2[v];

                    return ret;
                });

                var ret = tmp[v][0];
                ret.LeftID = tmp[v][0].TPRID;
                ret.PRINCIPAL_RISK = v;
                ret.RiskSubTypes = RiskSubTypes;
                ret.RiskSubTypesVal = tmp[v];

                return ret;
            });

            return res;
        }
    )
}

function getAllRisk(param) {
    return fetchWHeader(`/rfo/getlefttable`, param).then(
        res => {
            res.DataFlat = _.cloneDeep(res.Data);

            var tmp = _.groupBy(res.Data, "PRINCIPAL_RISK_TYPES")
            res.Data = _.map(Object.keys(tmp), function(v, i){
                var tmpTmp = _.cloneDeep(tmp[v]);

                var ret = tmpTmp[0];
                ret.ID = i;
                ret.PRINCIPAL_RISK_TYPESsVal = tmpTmp;
                ret.PRINCIPAL_RISK_TYPES = v;

                var tmp2 = _.groupBy(tmp[v], "RISK_SUB_TYPE");  
                ret.RISK_SUB_TYPEs = _.map(Object.keys(tmp2), function(w, j){
                    var tmpTmp2 = _.cloneDeep(tmp2[w]);

                    var ret = tmpTmp2[0];
                    ret.ID = j;
                    ret.RISK_SUB_TYPEsVal = tmpTmp2;
                    ret.RISK_SUB_TYPE = w;

                    return ret;
                });

                return ret;
            });

            res.Data.forEach(v => {
                v.RISK_SUB_TYPEs.shift();
            });
            
            return res;
        },
    );
}

function getPriorityTable(param) {
    return fetchWHeader(`/rfo/getprioritytable`, param).then(
        res => {
            res.Data = [
                {"CDE_NAME":"Maturity Date","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":2,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Annual Report - Risk Review Section","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n·Report provides Group-level risk–related disclosures to external stakeholders\n","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":1},
                {"CDE_NAME":"Collateral Location Code","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":2,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Annual Report - Risk Review Section","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n·Report provides Group-level risk–related disclosures to external stakeholders\n","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":1},
                {"CDE_NAME":"Customer Domicile Country Code","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":2,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Annual Report - Risk Review Section","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n·Report provides Group-level risk–related disclosures to external stakeholders\n","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":1},
                {"CDE_NAME":"Expected Exposure","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":2,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Annual Report - Risk Review Section","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n·Report provides Group-level risk–related disclosures to external stakeholders\n","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":1},
                {"CDE_NAME":"Guarantor's Location","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":2,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Annual Report - Risk Review Section","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n·Report provides Group-level risk–related disclosures to external stakeholders\n","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":1},
                {"CDE_NAME":"Short Term","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Limit","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":2,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Annual Report - Risk Review Section","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n·Report provides Group-level risk–related disclosures to external stakeholders\n","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":1},
                {"CDE_NAME":"Booking Country Code","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":2,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Annual Report - Risk Review Section","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n·Report provides Group-level risk–related disclosures to external stakeholders\n","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":1},
                {"CDE_NAME":"Outstanding","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":2,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Annual Report - Risk Review Section","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n·Report provides Group-level risk–related disclosures to external stakeholders\n","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":1},
                {"CDE_NAME":"Standard Product Code Description","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":2,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Annual Report - Risk Review Section","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n·Report provides Group-level risk–related disclosures to external stakeholders\n","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":1},
                {"CDE_NAME":"Transaction Currency","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":2,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Annual Report - Risk Review Section","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n·Report provides Group-level risk–related disclosures to external stakeholders\n","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":1},
                {"CDE_NAME":"Medium Term","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Limit","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":2,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Annual Report - Risk Review Section","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n·Report provides Group-level risk–related disclosures to external stakeholders\n","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":1},
                {"CDE_NAME":"MTM for SFTs","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":2,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Annual Report - Risk Review Section","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n·Report provides Group-level risk–related disclosures to external stakeholders\n","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":1},
                {"CDE_NAME":"Short Term","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Limit","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Medium Term","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Limit","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Transaction Currency","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Standard Product Code Description","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Outstanding","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Not Applicable","CDE_RATIONALE":" ","CRM_NAME":"Tier 1 Capital","CRM_RATIONALE":"These CRM are added in 2018 in relation to the Risk Appetite (RA) Metrics applicable for Country Risk. Enterprise level RA metrics are introduced to integrate RA with stress testing and to incorporate credit loan impairment and operational losses. The ownership of RA metrics lies with the Management Team.","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"MTM for SFTs","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Guarantor's Location","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Expected Exposure","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Customer Domicile Country Code","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Collateral Location Code","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Booking Country Code","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Not applicable","CDE_RATIONALE":" ","CRM_NAME":"Sovereign Rating","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Customer Domicile Country Code","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Single Country Risk Exposure (SCRE)","CRM_RATIONALE":"These CRM are added in 2018 in relation to the Risk Appetite (RA) Metrics applicable for Country Risk. Enterprise level RA metrics are introduced to integrate RA with stress testing and to incorporate credit loan impairment and operational losses. The ownership of RA metrics lies with the Management Team.","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Tier 1 Capital","CDE_RATIONALE":" ","CRM_NAME":"Single Country Medium Term (SCMT) Ratio","CRM_RATIONALE":"These CRM are added in 2018 in relation to the Risk Appetite (RA) Metrics applicable for Country Risk. Enterprise level RA metrics are introduced to integrate RA with stress testing and to incorporate credit loan impairment and operational losses. The ownership of RA metrics lies with the Management Team.","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Single Country Risk Exposure (SCRE)","CDE_RATIONALE":" ","CRM_NAME":"Single Country Medium Term (SCMT) Ratio","CRM_RATIONALE":"These CRM are added in 2018 in relation to the Risk Appetite (RA) Metrics applicable for Country Risk. Enterprise level RA metrics are introduced to integrate RA with stress testing and to incorporate credit loan impairment and operational losses. The ownership of RA metrics lies with the Management Team.","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Medium Term","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Single Country Medium Term (SCMT) Ratio","CRM_RATIONALE":"These CRM are added in 2018 in relation to the Risk Appetite (RA) Metrics applicable for Country Risk. Enterprise level RA metrics are introduced to integrate RA with stress testing and to incorporate credit loan impairment and operational losses. The ownership of RA metrics lies with the Management Team.","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Maturity Date","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Cross Border Exposure (CCBE)","CRM_RATIONALE":"CRMs are  defined as  calculated or computed value or an aggregation of data elements that forms an integral part of risk information. The rationale for  identification of this CRM,are as follows: ·The measure is  used for Country  risk reporting and decision making to manage risk appetite and  further used to calculate the risk tolerance metric that is published in the Group Risk Information Report \n· Variance thresholds exist for the identified measure and any threshold breaches\nrequire attention and exception management\n· The measure is critical for decisions during a crisis situation","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Tier 1 Capital","CDE_RATIONALE":" ","CRM_NAME":"Single Country Cross Border Exposure (SCCBE)","CRM_RATIONALE":"These CRM are added in 2018 in relation to the Risk Appetite (RA) Metrics applicable for Country Risk. Enterprise level RA metrics are introduced to integrate RA with stress testing and to incorporate credit loan impairment and operational losses. The ownership of RA metrics lies with the Management Team.","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Single Country Risk Exposure (SCRE)","CDE_RATIONALE":" ","CRM_NAME":"Single Country Cross Border Exposure (SCCBE)","CRM_RATIONALE":"These CRM are added in 2018 in relation to the Risk Appetite (RA) Metrics applicable for Country Risk. Enterprise level RA metrics are introduced to integrate RA with stress testing and to incorporate credit loan impairment and operational losses. The ownership of RA metrics lies with the Management Team.","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Customer Domicile Country Code","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Single Country Cross Border Exposure (SCCBE)","CRM_RATIONALE":"These CRM are added in 2018 in relation to the Risk Appetite (RA) Metrics applicable for Country Risk. Enterprise level RA metrics are introduced to integrate RA with stress testing and to incorporate credit loan impairment and operational losses. The ownership of RA metrics lies with the Management Team.","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Single Country Risk Exposure (SCRE)","CDE_RATIONALE":" ","CRM_NAME":"Country Risk Concentration Ratio (CRC)","CRM_RATIONALE":"These CRM are added in 2018 in relation to the Risk Appetite (RA) Metrics applicable for Country Risk. Enterprise level RA metrics are introduced to integrate RA with stress testing and to incorporate credit loan impairment and operational losses. The ownership of RA metrics lies with the Management Team.","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Customer Domicile Country Code","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Country Risk Concentration Ratio (CRC)","CRM_RATIONALE":"These CRM are added in 2018 in relation to the Risk Appetite (RA) Metrics applicable for Country Risk. Enterprise level RA metrics are introduced to integrate RA with stress testing and to incorporate credit loan impairment and operational losses. The ownership of RA metrics lies with the Management Team.","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Country Cross Border Exposure (CCBE)","CDE_RATIONALE":" ","CRM_NAME":"Country Risk Concentration Ratio (CRC)","CRM_RATIONALE":"These CRM are added in 2018 in relation to the Risk Appetite (RA) Metrics applicable for Country Risk. Enterprise level RA metrics are introduced to integrate RA with stress testing and to incorporate credit loan impairment and operational losses. The ownership of RA metrics lies with the Management Team.","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2},
                {"CDE_NAME":"Customer Domicile Country Code","CDE_RATIONALE":"This CDE is an attribute that contributes to the calculation or representation of a CRM(ie.Country Cross Border Exposure) and any data element changes  for this CDE will have a significant impact on the associated CRM.","CRM_NAME":"Single Country Medium Term (SCMT) Ratio","CRM_RATIONALE":"These CRM are added in 2018 in relation to the Risk Appetite (RA) Metrics applicable for Country Risk. Enterprise level RA metrics are introduced to integrate RA with stress testing and to incorporate credit loan impairment and operational losses. The ownership of RA metrics lies with the Management Team.","ID":36,"PRINCIPAL_RISK":"Country","PRIORITY_REPORT":"Group Risk Information Report - GRIR","PRIORITY_REPORT_RATIONALE":"This Report is identified by Risk Control Owners as that is required for effective risk management by the Group in accordance with the Risk Management Framework. It includes one or more CRMs and meets the following criteria:\n· Report is used for effective risk management to set risk appetite in line with strategic objectives\n· Report is used to monitor material risks\n· Report is used to keep the Group’s risk profile within its risk tolerance and risk appetite boundaries\n· Report is used during a crisis situation\n· Report is expanded to include Risk Appetite Matrics","PR_COUNT":2,"RESULT_COUNT":2,"RISK_SUB":"Country Cross Border Risk","R__":2}
            ]

            res.DataFlat = _.cloneDeep(res.Data);

            var tmp = _.groupBy(res.Data, "PRIORITY_REPORT")
            res.Data = _.map(Object.keys(tmp), function(v, i){
                var tmpTmp = _.cloneDeep(tmp[v]);

                var ret = tmpTmp[0];
                ret.ID = i;
                ret.PRIORITY_REPORTsVal = tmpTmp;
                ret.PRIORITY_REPORT = v;

                var tmp2 = _.groupBy(tmp[v], "PRIORITY_REPORT_RATIONALE");  
                ret.PRIORITY_REPORT_RATIONALEs = _.map(Object.keys(tmp2), function(w, j){
                    var tmpTmp2 = (tmp2[w]);

                    var ret = tmpTmp2[0];
                    ret.ID = j;
                    ret.PRIORITY_REPORT_RATIONALEsVal = tmpTmp2;
                    ret.PRIORITY_REPORT_RATIONALE = w;

                    return ret;
                });

                var tmp3 = _.groupBy(tmp[v], "CRM_NAME");  
                console.log(tmp3);
                
                ret.CRM_NAMEs = _.map(Object.keys(tmp3), function(w, j){
                    var tmpTmp3 = (tmp3[w]);

                    var ret = tmpTmp3[0];
                    ret.ID = j;
                    ret.CRM_NAMEsVal = tmpTmp3;
                    ret.CRM_NAME = w;

                    return ret;
                });

                var tmp4 = _.groupBy(tmp[v], "CRM_RATIONALE");  
                ret.CRM_RATIONALEs = _.map(Object.keys(tmp4), function(w, j){
                    var tmpTmp4 = (tmp4[w]);

                    var ret = tmpTmp4[0];
                    ret.ID = j;
                    ret.CRM_RATIONALEsVal = tmpTmp4;
                    ret.CRM_RATIONALE = w;

                    return ret;
                });

                var tmp5 = _.groupBy(tmp[v], "CDE_NAME");  
                ret.CDE_NAMEs = _.map(Object.keys(tmp5), function(w, j){
                    var tmpTmp5 = (tmp5[w]);

                    var ret = tmpTmp5[0];
                    ret.ID = j;
                    ret.CDE_NAMEsVal = tmpTmp5;
                    ret.CDE_NAME = w;

                    return ret;
                });

                return ret;
            });

            res.Data.forEach(v => {
                var lengths = [v.PRIORITY_REPORT_RATIONALEs.length, v.CRM_NAMEs.length, v.CRM_RATIONALEs.length, v.CDE_NAMEs.length];
                v.rowspanAcuan = math.lcm(...lengths);

                v.childrenRow = [];
                for (let i = 0; i < v.rowspanAcuan; i++) {
                    var inject = (valName) => {
                        if (i % (v.rowspanAcuan / v[valName + "s"].length) == 0){
                            return v[valName + "s"][(i / (v.rowspanAcuan / v[valName + "s"].length))][valName];
                        }

                        return null;
                    }

                    var row = {
                        PRIORITY_REPORT_RATIONALE: inject("PRIORITY_REPORT_RATIONALE"),
                        CRM_NAME: inject("CRM_NAME"),
                        CRM_RATIONALE: inject("CRM_RATIONALE"),
                        CDE_NAME: inject("CDE_NAME"),
                        CDE_RATIONALE: inject("CDE_NAME"),
                    }

                    v.childrenRow.push(row);
                }
                v.childrenRow.shift();
                
                v.expanded = false;
            });
            
            console.log(res.Data);
            
            return res;
        },
    );
}